### ISSUE TITLE
The 1.2.0 release is missing from Ansible Galaxy

### ISSUE THREAD

**Issue by timway** [ansible-collections/dellemc.os10#128]
##### SUMMARY
The latest release available on Ansible Galaxy is 1.1.1. A GitHub release was published for 1.2.0 and I was unaware of it until I went searching around since I normally default to looking at Galaxy first for this information.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Ansible Galaxy

##### ANSIBLE VERSION
```bash
$ ansible-galaxy --version
ansible-galaxy [core 2.12.6]
```

##### CONFIGURATION
Irrelevant

##### OS / ENVIRONMENT
Irrelevant

##### STEPS TO REPRODUCE

```bash
ansible-galaxy collection install dellemc.os10
```

##### EXPECTED RESULTS
The 1.2.0 collection is installed

##### ACTUAL RESULTS
The 1.1.0 collection is installed

**Comment by kongslund** [comment]
Also, Ansible 6.1.0 bundles dellemc.os10 version 1.1.1, probably as a result of the release not being present on Ansible Galaxy.

**Comment by prasadapr** [comment]
HI @timway, the latest version 1.2.2 available in the Ansible Galaxy. Issued the below command to install the latest ansible collections: 
`ansible-galaxy collection install dellemc.os10
`
we have not observed any issues, when issue the above command and its installed latest version 1.2.2 successfully.

Issue the below command, to see what is the latest collection version installed:
`ansible-galaxy collection list dellemc.os10`

**Comment by prasadapr** [comment]
**Hi @timway,** if its working shall we close this issue.

**Comment by timway** [comment]
Thanks @prasadapr , I can confirm I get 1.2.3 from galaxy now so you must've pushed another version since your post on here. All good, thanks!

**Comment by timway** [comment]
Closing as resolved.

**Comment by prasadapr** [comment]
Hi @timway, Thank you for closing the issue.
