### ISSUE TITLE
os10_interface errors when trying to configure a VLAN due to the "negotiation" command

### ISSUE THREAD

**Issue by irgama** [ansible-collections/dellemc.os10#146]
##### SUMMARY
Configuring VLANs with the OS10 interface role errors out due to trying to run "no negotiation" on an interface where that cannot be configured.  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os10_interface role

##### ANSIBLE VERSION
ansible [core 2.14.4]
  config file = /var/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.16 (main, Mar 29 2023, 03:56:49) [GCC 8.5.0 20210514 (Red Hat 8.5.0-16)] (/usr/local/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True

##### COLLECTION VERSION
1.2.0

##### OS / ENVIRONMENT
UBI8, configuring Dell OS10 10.5.5

##### STEPS TO REPRODUCE
Create an inventory where you configure any VLAN, and run the playbook. 
os10_interface:
  vlan 1:
    admin: down

##### EXPECTED RESULTS
TASK [dellemc.os10.os10_interface : Provisioning interface configuration for os10] ***************************************************
changed: [extsw]

##### ACTUAL RESULTS
TASK [dellemc.os10.os10_interface : Provisioning interface configuration for os10] *****************************************
fatal: [extsw]: FAILED! => changed=false
  command: no negotiation
  msg: |-
    no negotiation
    % Error: Unrecognized command.
    extsw(conf-if-vl-1)#
  rc: -32603

PLAY RECAP *****************************************************************************************************************
extsw                      : ok=2    changed=2    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0

**Comment by sc68cal** [comment]
#134 probably fixes

**Comment by irgama** [comment]
It does, closing.

**Comment by sc68cal** [comment]
It hasn't been merged yet so it's still an issue
