### ISSUE TITLE
Collection name & publishing

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/dellemc.os10#20]
Hi,
This issue applies to os6,os9, and os10

1) It looks like you've renamed the namespace, can you please deprecate the old version in https://galaxy.ansible.com/dellemc_networking

2) Can you please raise a PR to do a search and replace update ansible/ansible's `lib/ansible/config/ansible_builtin_runtime.yml` from `dellemc_networking` to `dellemc`. This needs merging into `master` *and* a backport to `stable-2.10` branch

3) Please check with your legal team as you've license the collection as Apache 2.0, where as the content that was previously in github.com/ansible/ansible was under GPLv3+ (with parts under BSD).

4) When can I expect to see an initial publish of these three collections under the new namespace? 
We had to miss them out from the `ansible 2.10 alpha 1` build, https://groups.google.com/forum/#!topic/ansible-devel/uhJPpe_Wcuc

5) Please add sanity testing against `stable-2.10` at a minimum. You can achieve this by copying https://github.com/ansible-collections/collection_template/blob/master/.github/workflows/ansible-test.yml into your repos

**Comment by gundalow** [comment]
If you copy that file into each of the repos you will get sanity testing

**Comment by gundalow** [comment]
Copy into .github/workflows/ansible-test.yml

**Comment by javeedf** [comment]
@gundalow Created PR to address point2
https://github.com/ansible/ansible/pull/70299

**Comment by gundalow** [comment]
@javeedf when can we expect dellos6&9 to be published https://galaxy.ansible.com/dellemc_networking

**Comment by javeedf** [comment]
> @javeedf when can we expect dellos6&9 to be published https://galaxy.ansible.com/dellemc_networking

@gundalow  we will be publishing by end of this month. Moving forward will use https://galaxy.ansible.com/dellemc

**Comment by gundalow** [comment]
Could we possible get a `0.1.0` release of these three collections done this week so we can include them in the next `ansible` Alpha build?
Otherwise we will be force to add the dellos modules back into community.network https://github.com/ansible-collections/community.network/pull/91

**Comment by javeedf** [comment]
Sure @gundalow we will try to add it in a week

**Comment by javeedf** [comment]
@gundalow 

**Question1:** already code is available in Github, is that not enough? 
https://github.com/ansible-collections/dellemc.os6
https://github.com/ansible-collections/dellemc.os9

**Question:2** we are also developing new sonic? when is the timeline to add that into Alpha build?
https://github.com/ansible-collections/dellemc.sonic

**Comment by parkrish** [comment]
> Could we possible get a `0.1.0` release of these three collections done this week so we can include them in the next `ansible` Alpha build?
> Otherwise we will be force to add the dellos modules back into community.network [ansible-collections/community.network#91](https://github.com/ansible-collections/community.network/pull/91)

@gundalow Do you want us to release as 0.1.0 or releasing as 0.1.0-dev1 is fine ?

**Comment by felixfontein** [comment]
Out of curiosity: how will the collections be named? This collection (dellemc.os10) seems to be called dellemc_networking.os10 on galaxy. Will the collections for os6 and os9 also use that galaxy namespace? Or are you planning to switch to dellemc? If yes, you should decide and announce that soon, because we just changed the dellemc.os10 references to dellemc_networking.os10 in Ansible's ansible_builtin_runtime.yml.

**Comment by gundalow** [comment]
@javeedf Hi,
Answer 1: Unfortunately not, we need this published to Galaxy

Answer 2: In Ansible 2.10, we are only including collections which contained modules that were in Ansible 2.9.
I don't believe there were any Sonic modules in Ansible 2.9, therefore we will not include the Sonic collection in Ansible 2.10

**Comment by parkrish** [comment]
> Out of curiosity: how will the collections be named? This collection (dellemc.os10) seems to be called dellemc_networking.os10 on galaxy. Will the collections for os6 and os9 also use that galaxy namespace? Or are you planning to switch to dellemc? If yes, you should decide and announce that soon, because we just changed the dellemc.os10 references to dellemc_networking.os10 in Ansible's ansible_builtin_runtime.yml.

The dellemc_networking.os10 in galaxy will be deprecated.The dellemc.os6, dellemc.os9 and dellemc.os10 collections will be published to the galaxy soon

**Comment by felixfontein** [comment]
Since RC1 of ansible-base is supposed to be released tomorrow, it would probably be good if the collections under the dellemc namespace could be published on galaxy **today**.

**Comment by parkrish** [comment]
Have published dellemc.os10 collections version 0.1.0-dev1 (https://galaxy.ansible.com/dellemc/os10)

**Comment by komalupatil** [comment]
@gundalow ,

Getting the below error while trying to run the sanity test on ansible version 2.10.0b1.post0 for Dell EMC OS9. 

Running sanity test 'validate-modules' with Python 3.6
ERROR: Found 3 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/os9_command.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'No module named 'ansible.module_utils.network''
ERROR: plugins/modules/os9_config.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'No module named 'ansible.module_utils.network''
ERROR: plugins/modules/os9_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'No module named 'ansible.module_utils.network''

@skg-net 

Regards,
Komal

**Comment by javeedf** [comment]
@komalupatil please add this part of ignore.txt

similar to https://github.com/ansible-collections/dellemc.sonic/blob/master/tests/sanity/ignore-2.10.txt

**Comment by gundalow** [comment]
@komalupatil I think the import line needs updating to be like: https://github.com/ansible-collections/dellemc.os10/blob/c0fc33e15bf8315c0a836e641bb6175cc8cef9ad/plugins/modules/os10_facts.py#L131

**Comment by gundalow** [comment]
> @komalupatil please add this part of ignore.txt
> 
> similar to https://github.com/ansible-collections/dellemc.sonic/blob/master/tests/sanity/ignore-2.10.txt

Generally speaking, having anything in `ignore-x.y.txt` is a bug. The underlying issue should be fixed.

**Comment by gundalow** [comment]
> @gundalow ,
> 
> Getting the below error while trying to run the sanity test on ansible version 2.10.0b1.post0 for Dell EMC OS9. 

If you raise the PR in the os9 repo we can all take a look

**Comment by parkrish** [comment]
@gundalow , I see that the Ansible docs for collections(https://docs.ansible.com/ansible/2.10/collections/index.html) list dellemc_networking.os10 which has been deprecated and replaced by dellemc.os10. Can you please refer to the dellemc.os10 docs instead of the dellemc_networking.os10 ?

**Comment by felixfontein** [comment]
@parkrish that will automatically happen when the docs are rebuilt after the next alpha version is released (the current one accidentally still contained dellemc_networking.os10 instead of dellemc.os10).

**Comment by felixfontein** [comment]
What's the current state with dellemc.os6 and dellemc.os9? There are still no releases at galaxy.

**Comment by gundalow** [comment]
Looks like `1.0.0` of dellemc.os6 and dellemc.os9 has just been released. Thank you
https://galaxy.ansible.com/dellemc

**Comment by parkrish** [comment]
@gundalow , @felixfontein , Yes, we just published os6 and os9 collections to galaxy. Thanks for your valuable inputs throughout.
Can we close this issue now ?

**Comment by gundalow** [comment]
@parkrish could you please confirm that 1-6 have been completed for the three repos?

**Comment by parkrish** [comment]
@gundalow , we have taken care of the points raised in the issue.

**Comment by parkrish** [comment]
The OS6, OS9 and OS10 collections have been published to Ansible-galaxy.
