### ISSUE TITLE
Imports to collection that does not exist

### ISSUE THREAD

**Issue by AlanCoding** [ansible-collections/dellemc.os10#22]
##### SUMMARY
https://github.com/ansible-collections/dellemc.os10/blob/ee48d78c84d1893ff88148298cb12f29621c4812/plugins/modules/os10_config.py#L213-L216

The collection `dellemc.os10` does not exist anywhere I can think to look.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
plugins/modules/os10_config.py

##### ANSIBLE VERSION
2.9

##### CONFIGURATION
defaults

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
Try to run or import module

##### EXPECTED RESULTS
imports from own collection, or from declared dependencies

##### ACTUAL RESULTS
the collection imported from is not a dependency (and probably doesn't exist)

It might have been intended to import from here instead:

https://github.com/ansible-collections/dellemc.os10/blob/ee48d78c84d1893ff88148298cb12f29621c4812/plugins/module_utils/network/os10.py

So that would be a simple change `dellemc.os10` --> `dellemc_networking.os10`

**Comment by parkrish** [comment]
dellemc_networking.os10 is being migrated to dellemc.os10.   dellemc.os10  will be published soon.

**Comment by AlanCoding** [comment]
I didn't know that background, will close
