### ISSUE TITLE
os10_vlan role cannot configure vlan interfaces because of os10_vlan.j2 issue

### ISSUE THREAD

**Issue by fschaer** [ansible-collections/dellemc.os10#53]
##### SUMMARY

It looks like the os10_vlan role cannot handle configurations at all : it collapses interfaces names anad removes all spaces, causing interface names such as "range ethernet 1/1/1-1/1/2" to become "rangeethernet1/1/1-1/1/2"

This is caused by these split() | join() statements which actually remove all spaces.

https://github.com/ansible-collections/dellemc.os10/blob/1f2668f38957d873e2b9a6d3726941d93a358c7d/roles/os10_vlan/templates/os10_vlan.j2#L91

https://github.com/ansible-collections/dellemc.os10/blob/1f2668f38957d873e2b9a6d3726941d93a358c7d/roles/os10_vlan/templates/os10_vlan.j2#L104

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

~/.ansible/collections/ansible_collections/dellemc/os10/roles/os10_vlan/templates/os10_vlan.j2

##### ANSIBLE VERSION
```
$ ansible --version
/home/fred/.local/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature
ansible 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/fred/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fred/.local/lib/python2.7/site-packages/ansible
  executable location = /home/fred/.local/bin/ansible
  python version = 2.7.17 (default, Sep 30 2020, 13:38:04) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
/home/fred/.local/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature
ANSIBLE_SSH_ARGS(/home/fred/ansible/network/ansible.cfg) = -o ControlMaster=no
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /home/fred/ansible.log
DEFAULT_ROLES_PATH(/home/fred/ansible/network/ansible.cfg) = [u'/home/fred/ansible/network']
DEFAULT_TIMEOUT(/home/fred/ansible/network/ansible.cfg) = 60
HOST_KEY_CHECKING(/home/fred/ansible/network/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/fred/ansible/network/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(env: ANSIBLE_PERSISTENT_CONNECT_TIMEOUT) = 60

```

##### OS / ENVIRONMENT

Trying to configure a new s4148T-ON switch from an Ubuntu 18.04 VM, to os10 v10.5.0.4 vanilla OS.

##### STEPS TO REPRODUCE

Just configure vlan interfaces

```yaml
os10_vlan:
  vlan 456:
    untagged_members:
    - port: range ethernet 1/1/1-1/1/24
```

##### EXPECTED RESULTS

Vlans should be configured with member interfaces

##### ACTUAL RESULTS

Vlan configuration failure with error : 
```
"msg": "interface rangeethernet1/1/1-1/1/24\r\n% Error: Illegal parameter.\r\n\u0007dapcom18(conf-if-vl-456)# "
```

##### Additional notes

Replacing offending lines as follows fixes the configuration issues : 

```
# ansible-galaxy collection install dellemc.os10
# (...)
$ diff ~/.ansible/collections/ansible_collections/dellemc/os10/roles/os10_vlan/templates/os10_vlan.j2{.old,}
91c91
< interface {{ ports.port.split() | join() }}
---
> interface {{ ports.port }}
104c104
< interface {{ ports.port.split() | join() }}
---
> interface {{ ports.port }}
```

==> I'm sure these split | join are here for a reason, but it seems to me these are breaking stuff ?

**Comment by gunasekaran-t** [comment]
@fschaer Thanks for pointing the issue. The `split` and `join` are added to handle idempotency. I understand that this doesnt work for interface range in member ports. We are working on handling same. However it should work by specifying individual ports separately as given in the examples. 

```
os10_vlan:
  vlan 456:
    untagged_members:
      - port: ethernet 1/1/1
        state: present
      - port: ethernet 1/1/2
        state: present
```

**Comment by fschaer** [comment]
Hi,

Yes, I thought it would work too ... it's just that having a single "range ethernet 1 -> 48" statement is much more simple than having to write 48 or even more yaml statements  ;)
