### ISSUE TITLE
Timeout for os10_config commands with yes/no prompt such as ip http vrf

### ISSUE THREAD

**Issue by fmkaiser** [ansible-collections/dellemc.os10#91]
##### SUMMARY
The OS10 `ip http vrf <vrf>` command (any maybe others) displays a yes/no prompt, leading to a failure (timeout) when used in os10_config:

```
os10-sw1(config)# ip http vrf management
% Warning: HTTP client will be disabled in default VRF and enabled on management VRF
Do you want to continue ? [yes/no(default)]:
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`os10_config`

##### ANSIBLE VERSION
```
ansible [core 2.11.2] 
  python version = 3.6.8 (default, Nov 10 2020, 07:30:01) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION
```
Collection   Version
------------ -------
dellemc.os10 1.1.1 
```

##### CONFIGURATION
```
NETWORK_GROUP_MODULES(/etc/ansible/ansible.cfg) = ['os10']
```

##### OS / ENVIRONMENT

```
Dell S5248F-ON with OS10 10.5.2.6
```

##### STEPS TO REPRODUCE
```
os10_config:
        lines: ['ip http vrf management']

-> 

fatal: [os10-sw1]: FAILED! => {
    "changed": false,
    "command": "ip http vrf management",
    "msg": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide.",
    "rc": -32603
}
```

**Comment by sc68cal** [comment]
You should use the `prompt` argument

https://docs.ansible.com/ansible/latest/network/user_guide/network_working_with_command_output.html

**Comment by fmkaiser** [comment]
Thanks @sc68cal for the hint about the `prompt` argument!

I had not found any information about it in the os10_config documentation.  
A mention in [docs/dellemc.os10.os10_config_module.rst](docs/dellemc.os10.os10_config_module.rst) might be useful. 

I now managed to get it working like this:
```
os10_config:
    lines:
      - command: 'ip http vrf management'
        prompt: '.*Do you want to continue.*'
        answer: 'yes'
```

**Comment by sc68cal** [comment]
Yeah the Ansible documentation is good in some places, but I feel like the Ansible Network documentation is a bit scattered

**Comment by prasadapr** [comment]
@fmkaiser, Tried with above config and its working as expected.

root@Ubuntu20-vm-038-037:~/os10-ansible# cat ip_http_vrf_timeout_issue-91.yaml
---
- name: configurep http vrf managemen
  hosts: datacenter
  gather_facts: false
  connection: network_cli
  collections:
   - dellemc.os10
  tasks:
   - name: configure ip http vrf management
     os10_config:
       lines:
         - command: 'ip vrf management'
           command: 'ip http vrf management'
           prompt: '.*Do you want to continue.*'
           answer: 'yes'

root@Ubuntu20-vm-038-037:~/os10-ansible#  


Execution logs:

root@Ubuntu20-vm-038-037:~/os10-ansible# ansible-playbook -i inventory.yaml ip_http_vrf_timeout_issue-91.yaml  -vvv
ansible-playbook [core 2.12.0]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
No config file found; using defaults
host_list declined parsing /root/os10-ansible/inventory.yaml as it did not pass its verify_file() method
script declined parsing /root/os10-ansible/inventory.yaml as it did not pass its verify_file() method
Parsed /root/os10-ansible/inventory.yaml inventory source with ini plugin
[WARNING]: While constructing a mapping from /root/os10-ansible/ip_http_vrf_timeout_issue-91.yaml, line 13, column 12, found a duplicate dict key (command). Using last defined value only.
redirecting (type: action) dellemc.os10.os10_config to dellemc.os10.os10
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: ip_http_vrf_timeout_issue-91.yaml *************************************************************************************************************************************************************************************
1 plays in ip_http_vrf_timeout_issue-91.yaml

PLAY [configurep http vrf managemen] ********************************************************************************************************************************************************************************************
META: ran handlers
redirecting (type: action) dellemc.os10.os10_config to dellemc.os10.os10
[WARNING]: Collection ansible.netcommon does not support Ansible version 2.12.0

TASK [configure ip http vrf management] *****************************************************************************************************************************************************************************************
task path: /root/os10-ansible/ip_http_vrf_timeout_issue-91.yaml:10
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: action) dellemc.os10.os10_config to dellemc.os10.os10
redirecting (type: action) dellemc.os10.os10_config to dellemc.os10.os10
<100.104.40.187> ESTABLISH LOCAL CONNECTION FOR USER: root
<100.104.40.187> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-949694uva8fydf `"&& mkdir "` echo /root/.ansible/tmp/ansible-local-949694uva8fydf/ansible-tmp-1642585823.6559649-949701-247227427471952 `" && echo ansible-tmp-1642585823.6559649-949701-247227427471952="` echo /root/.ansible/tmp/ansible-local-949694uva8fydf/ansible-tmp-1642585823.6559649-949701-247227427471952 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/dellemc/os10/plugins/modules/os10_config.py
<100.104.40.187> PUT /root/.ansible/tmp/ansible-local-949694uva8fydf/tmpam0k_c9k TO /root/.ansible/tmp/ansible-local-949694uva8fydf/ansible-tmp-1642585823.6559649-949701-247227427471952/AnsiballZ_os10_config.py
<100.104.40.187> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-949694uva8fydf/ansible-tmp-1642585823.6559649-949701-247227427471952/ /root/.ansible/tmp/ansible-local-949694uva8fydf/ansible-tmp-1642585823.6559649-949701-247227427471952/AnsiballZ_os10_config.py && sleep 0'
<100.104.40.187> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-local-949694uva8fydf/ansible-tmp-1642585823.6559649-949701-247227427471952/AnsiballZ_os10_config.py && sleep 0'
<100.104.40.187> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-949694uva8fydf/ansible-tmp-1642585823.6559649-949701-247227427471952/ > /dev/null 2>&1 && sleep 0'
changed: [spine] => {
    "changed": true,
    "commands": [
        "{\"command\": \"ip http vrf management\", \"prompt\": \".*Do you want to continue.*\", \"answer\": \"yes\"}",
        "commit"
    ],
    "invocation": {
        "module_args": {
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "config": null,
            "lines": [
                {
                    "answer": "yes",
                    "command": "ip http vrf management",
                    "prompt": ".*Do you want to continue.*"
                }
            ],
            "match": "line",
            "parents": null,
            "provider": null,
            "replace": "line",
            "save": false,
            "src": null,
            "update": "merge"
        }
    },
    "saved": false,
    "updates": [
        "{\"command\": \"ip http vrf management\", \"prompt\": \".*Do you want to continue.*\", \"answer\": \"yes\"}",
        "commit"
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************************************************************************************************************
spine                      : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

root@Ubuntu20-vm-038-037:~/os10-ansible#

**Comment by prasadapr** [comment]
@fmkaiser, if we are good, shall we close this issue?

**Comment by fmkaiser** [comment]
@prasadapr Thanks for the recap! I had already forgotten about this issue. 
Indeed with the `prompt` argument things are working fine.
