### ISSUE TITLE
Documentation build is broken

### ISSUE THREAD

**Issue by grantcurell** [ansible-collections/dellemc.os10#99]
I'm filing this as a bug because it is going to require some sort of code fix to address - all of the documentation on [the Ansible site](https://docs.ansible.com/ansible/latest/collections/dellemc/os10/index.html#role-index) under Role Index is broken. Ex:

![image](https://user-images.githubusercontent.com/35169230/134695247-329452cc-96e7-4562-9c1a-12c9860a0818.png)

**Comment by javeedf** [comment]
@gundalow  we have not changed any code for the last few months. not sure what went wrong, Could you please help on this issue?

**Comment by Andersson007** [comment]
looking

**Comment by Andersson007** [comment]
fixed on `devel` with https://github.com/ansible-community/antsibull/pull/310. We expect same for `latest` later when the doc will be generated for that version.

**Comment by javeedf** [comment]
@Andersson007 Thank you for closing this
